import type { AdmAutoadmisionEmailTemplate } from './adm_autoadmision.type';
import type { AdmBienvenidaEmailTemplate } from './adm_bienvenida.type';
import type { AdmCitasTurnosEmailTemplate } from './adm_citas_turnos.type';
import type { AdmDocumentoDerivacionAprobadoEmailTemplate } from './adm_documento_derivacion_aprobado.type';
import type { AdmDocumentoDerivacionPendienteEmailTemplate } from './adm_documento_derivacion_pendiente.type';
import type { AdmDocumentoDerivacionRechazadoEmailTemplate } from './adm_documento_derivacion_rechazado.type';
import type { AdmReagendamientoEmailTemplate } from './adm_reagendamiento.type';
import type { AdmRecordatorioCitaEmailTemplate } from './adm_recordatorio_cita.type';
import type { BaseEmailTemplate } from './base.type';
import type { EmailTemplateType } from './email_template_types.type';
import type { FacFacturaListaEmailTemplate } from './fac_factura_lista.type';
import type { HisCertificadoMedicoEmailTemplate } from './his_certificado_medico.type';
import type { HisProgramacionQuirofanoEmailTemplate } from './his_programacion_quirofano.type';
import type { HisRecetaMedicaEmailTemplate } from './his_receta_medica.type';
import type { HisResultadoExamenImagenEmailTemplate } from './his_resultado_examen_imagen.type';
import type { HisResultadoExamenLaboratorioEmailTemplate } from './his_resultado_examen_laboratorio.type';
import type { HisResultadoExamenPatologiaEmailTemplate } from './his_resultado_examen_patologia.type';
import type { HisSolicitudExamenImagenEmailTemplate } from './his_solicitud_examen_imagen.type';
import type { HisSolicitudExamenLaboratorioEmailTemplate } from './his_solicitud_examen_laboratorio.type';
import type { HisSolicitudExamenPatologiaEmailTemplate } from './his_solicitud_examen_patologia.type';
import type { MktCotizacionEmailTemplate } from './mkt_cotizacion.type';
import type { PinLoginEmailTemplate } from './pin_login.type';
import type { PinRecoveryEmailTemplate } from './pin_recovery.type';
import type { PinRegisterEmailTemplate } from './pin_register.type';
import type { PinResultEmailTemplate } from './pin_result.type';

export type EmailTemplatesTypesMap = {
  [EmailTemplateType.adm_autoadmision]: AdmAutoadmisionEmailTemplate;
  [EmailTemplateType.adm_bienvenida]: AdmBienvenidaEmailTemplate;
  [EmailTemplateType.adm_citas_turnos]: AdmCitasTurnosEmailTemplate;
  [EmailTemplateType.adm_documento_derivacion_aprobado]: AdmDocumentoDerivacionAprobadoEmailTemplate;
  [EmailTemplateType.adm_documento_derivacion_pendiente]: AdmDocumentoDerivacionPendienteEmailTemplate;
  [EmailTemplateType.adm_documento_derivacion_rechazado]: AdmDocumentoDerivacionRechazadoEmailTemplate;
  [EmailTemplateType.adm_reagendamiento]: AdmReagendamientoEmailTemplate;
  [EmailTemplateType.adm_recordatorio_cita]: AdmRecordatorioCitaEmailTemplate;
  [EmailTemplateType.base]: BaseEmailTemplate;
  [EmailTemplateType.fac_factura_lista]: FacFacturaListaEmailTemplate;
  [EmailTemplateType.his_certificado_medico]: HisCertificadoMedicoEmailTemplate;
  [EmailTemplateType.his_programacion_quirofano]: HisProgramacionQuirofanoEmailTemplate;
  [EmailTemplateType.his_receta_medica]: HisRecetaMedicaEmailTemplate;
  [EmailTemplateType.his_resultado_examen_imagen]: HisResultadoExamenImagenEmailTemplate;
  [EmailTemplateType.his_resultado_examen_laboratorio]: HisResultadoExamenLaboratorioEmailTemplate;
  [EmailTemplateType.his_resultado_examen_patologia]: HisResultadoExamenPatologiaEmailTemplate;
  [EmailTemplateType.his_solicitud_examen_imagen]: HisSolicitudExamenImagenEmailTemplate;
  [EmailTemplateType.his_solicitud_examen_laboratorio]: HisSolicitudExamenLaboratorioEmailTemplate;
  [EmailTemplateType.his_solicitud_examen_patologia]: HisSolicitudExamenPatologiaEmailTemplate;
  [EmailTemplateType.mkt_cotizacion]: MktCotizacionEmailTemplate;
  [EmailTemplateType.pin_login]: PinLoginEmailTemplate;
  [EmailTemplateType.pin_recovery]: PinRecoveryEmailTemplate;
  [EmailTemplateType.pin_register]: PinRegisterEmailTemplate;
  [EmailTemplateType.pin_result]: PinResultEmailTemplate;
};
