export enum EmailTemplateType {
  base = 'base',
  pin_login = 'pin_login',
  pin_recovery = 'pin_recovery',
  pin_register = 'pin_register',
  pin_result = 'pin_result',
  mkt_cotizacion = 'mkt_cotizacion',
  adm_autoadmision = 'adm_autoadmision',
  adm_citas_turnos = 'adm_citas_turnos',
  adm_documento_derivacion_aprobado = 'adm_documento_derivacion_aprobado',
  adm_documento_derivacion_rechazado = 'adm_documento_derivacion_rechazado',
  adm_documento_derivacion_pendiente = 'adm_documento_derivacion_pendiente',
  adm_reagendamiento = 'adm_reagendamiento',
  adm_recordatorio_cita = 'adm_recordatorio_cita',
  adm_bienvenida = 'adm_bienvenida',
  fac_factura_lista = 'fac_factura_lista',
  his_certificado_medico = 'his_certificado_medico',
  his_receta_medica = 'his_receta_medica',
  his_programacion_quirofano = 'his_programacion_quirofano',
  his_resultado_examen_laboratorio = 'his_resultado_examen_laboratorio',
  his_resultado_examen_imagen = 'his_resultado_examen_imagen',
  his_resultado_examen_patologia = 'his_resultado_examen_patologia',
  his_solicitud_examen_laboratorio = 'his_solicitud_examen_laboratorio',
  his_solicitud_examen_imagen = 'his_solicitud_examen_imagen',
  his_solicitud_examen_patologia = 'his_solicitud_examen_patologia',
}
